<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>body_69.5.1  7  3108 .  . .   .      7  202_bec67c</name>
   <tag></tag>
   <elementGuidId>ef27a917-0c11-485b-9d5a-abbb488f55fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='tinymce']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tinymce</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>body</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tinymce</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mce-content-body </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>mce_0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Rich Text Area. Press ALT-0 for help.</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>contenteditable</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>    ตามหนังสือที่ อว.69.5.1 ลงวันที่ 7 กันยายน 3108 ม.เเม่โจ้ กำหนดจัดโครงการ ............................................................................. โดยมีวัตถุประสงค์เพื่อ...................................................................................................................................... และได้เชิญข้าพเจ้า ผู้ช่วยศาสตราจารย์ ดร. สายัณห์ อุ่นนันกาศ เป็นวิทยากรเพื่อถ่ายทอดความรู้ เรื่อง ในระหว่างวันที่ 7 กันยายน 2022 ถึง 7 กันยายน 2022 ณ มหาวิทยาลัยเเม่โจ้ นั้น    ในการนี้  ข้าพเจ้าจึงขออนุญาตเข้าร่วมเป็นวิทยากรเพื่อถ่ายทอดความรู้ แก่ ...................................................... ในระหว่างวันที่ 7 กันยายน 2022 ถึง 7 กันยายน 2022 ณ มหาวิทยาลัยเเม่โจ้ ทั้งนี้    เดินทางโดยรถยนต์ส่วนตัวและขอเบิกค่าชดเชยน้ำมันเชื้อเพลิง </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tinymce&quot;)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_/iframe_Paragraph_mce_0_ifr</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//body[@id='tinymce']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//body[@id = 'tinymce' and (text() = '    ตามหนังสือที่ อว.69.5.1 ลงวันที่ 7 กันยายน 3108 ม.เเม่โจ้ กำหนดจัดโครงการ ............................................................................. โดยมีวัตถุประสงค์เพื่อ...................................................................................................................................... และได้เชิญข้าพเจ้า ผู้ช่วยศาสตราจารย์ ดร. สายัณห์ อุ่นนันกาศ เป็นวิทยากรเพื่อถ่ายทอดความรู้ เรื่อง ในระหว่างวันที่ 7 กันยายน 2022 ถึง 7 กันยายน 2022 ณ มหาวิทยาลัยเเม่โจ้ นั้น    ในการนี้  ข้าพเจ้าจึงขออนุญาตเข้าร่วมเป็นวิทยากรเพื่อถ่ายทอดความรู้ แก่ ...................................................... ในระหว่างวันที่ 7 กันยายน 2022 ถึง 7 กันยายน 2022 ณ มหาวิทยาลัยเเม่โจ้ ทั้งนี้    เดินทางโดยรถยนต์ส่วนตัวและขอเบิกค่าชดเชยน้ำมันเชื้อเพลิง ' or . = '    ตามหนังสือที่ อว.69.5.1 ลงวันที่ 7 กันยายน 3108 ม.เเม่โจ้ กำหนดจัดโครงการ ............................................................................. โดยมีวัตถุประสงค์เพื่อ...................................................................................................................................... และได้เชิญข้าพเจ้า ผู้ช่วยศาสตราจารย์ ดร. สายัณห์ อุ่นนันกาศ เป็นวิทยากรเพื่อถ่ายทอดความรู้ เรื่อง ในระหว่างวันที่ 7 กันยายน 2022 ถึง 7 กันยายน 2022 ณ มหาวิทยาลัยเเม่โจ้ นั้น    ในการนี้  ข้าพเจ้าจึงขออนุญาตเข้าร่วมเป็นวิทยากรเพื่อถ่ายทอดความรู้ แก่ ...................................................... ในระหว่างวันที่ 7 กันยายน 2022 ถึง 7 กันยายน 2022 ณ มหาวิทยาลัยเเม่โจ้ ทั้งนี้    เดินทางโดยรถยนต์ส่วนตัวและขอเบิกค่าชดเชยน้ำมันเชื้อเพลิง ')]</value>
   </webElementXpaths>
</WebElementEntity>
