<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_69.5.1  7  3108 .  . .   .      7  2022  7  2022</name>
   <tag></tag>
   <elementGuidId>ab628ed0-9c06-47df-a7cb-1747515a86ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='tinymce']/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>    ตามหนังสือที่ อว.69.5.1 ลงวันที่ 7 กันยายน 3108 ม.เเม่โจ้ กำหนดจัดโครงการ ............................................................................. โดยมีวัตถุประสงค์เพื่อ...................................................................................................................................... และได้เชิญข้าพเจ้า ผู้ช่วยศาสตราจารย์ ดร. สายัณห์ อุ่นนันกาศ เป็นวิทยากรเพื่อถ่ายทอดความรู้ เรื่อง ในระหว่างวันที่ 7 กันยายน 2022 ถึง 7 กันยายน 2022 ณ มหาวิทยาลัยเเม่โจ้ นั้น</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tinymce&quot;)/p[1]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_/iframe_Paragraph_mce_0_ifr</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='tinymce']/p</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = '    ตามหนังสือที่ อว.69.5.1 ลงวันที่ 7 กันยายน 3108 ม.เเม่โจ้ กำหนดจัดโครงการ ............................................................................. โดยมีวัตถุประสงค์เพื่อ...................................................................................................................................... และได้เชิญข้าพเจ้า ผู้ช่วยศาสตราจารย์ ดร. สายัณห์ อุ่นนันกาศ เป็นวิทยากรเพื่อถ่ายทอดความรู้ เรื่อง ในระหว่างวันที่ 7 กันยายน 2022 ถึง 7 กันยายน 2022 ณ มหาวิทยาลัยเเม่โจ้ นั้น' or . = '    ตามหนังสือที่ อว.69.5.1 ลงวันที่ 7 กันยายน 3108 ม.เเม่โจ้ กำหนดจัดโครงการ ............................................................................. โดยมีวัตถุประสงค์เพื่อ...................................................................................................................................... และได้เชิญข้าพเจ้า ผู้ช่วยศาสตราจารย์ ดร. สายัณห์ อุ่นนันกาศ เป็นวิทยากรเพื่อถ่ายทอดความรู้ เรื่อง ในระหว่างวันที่ 7 กันยายน 2022 ถึง 7 กันยายน 2022 ณ มหาวิทยาลัยเเม่โจ้ นั้น')]</value>
   </webElementXpaths>
</WebElementEntity>
